stages:
  - test
  - build

lint:
  stage: test
  image: docker-registry.wikimedia.org/golang
  before_script:
    - go get -u golang.org/x/lint/golint
  script:
    - make lint

unit:
  stage: test
  image: docker-registry.wikimedia.org/golang
  script:
    - make unit

build-image:
  stage: build
  tags: [buildkitd]
  image:
    name: moby/buildkit:master-rootless
    entrypoint: [ /bin/sh, -c ]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  script:
    - |-
      echo $FOO
      buildctl-daemonless.sh \
        build --frontend gateway.v0 \
        --opt source=docker-registry.wikimedia.org/wikimedia/blubber-buildkit:0.9.0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=.pipeline/blubber.yaml \
        --opt variant=test