image: docker-registry.wikimedia.org/golang:1.13-3

stages:
  - test
  - build

unittest:
  stage: test
  script:
    - make unit

lint:
  stage: test
  script:
    - make lint

build-blubberoid:
  stage: build
  script:
    - make blubberoid
