stages:
  - build

build-image:
  stage: build
  image:
    name: moby/buildkit:master-rootless
    entrypoint: [ /bin/sh, -c ]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  script:
    - |-
      buildctl-daemonless.sh \
        build --frontend gateway.v0 \
        --opt source=docker-registry.wikimedia.org/wikimedia/blubber-buildkit:0.9.0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=.pipeline/blubber.yaml \
        --opt variant=test