stages:
  - test
  - build

#lint:
#  stage: test
#  image: docker-registry.wikimedia.org/golang
#  before_script:
#    - go get -u golang.org/x/lint/golint
#  script:
#    - make lint
#
#unit:
#  stage: test
#  image: docker-registry.wikimedia.org/golang
#  script:
#    - make unit
#
build-image:
  stage: build
  tags: [buildkitd]
  image:
    name: moby/buildkit
    entrypoint: [ /bin/sh, -c ]
  script:
    - |-
      buildctl --tlscacert "$BUILDKITD_EVAL_CLIENT_CA" --tlscert "$BUILDKITD_EVAL_CLIENT_CERT" --tlskey "$BUILDKITD_EVAL_CLIENT_KEY" \
        build --frontend gateway.v0 \
        --opt source=docker-registry.wikimedia.org/wikimedia/blubber-buildkit:0.9.0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=.pipeline/blubber.yaml \
        --opt variant=test \
        --output type=image,name=registry.registry.svc.cluster.local/blubber:foo,registry.insecure=true,push=true
# foo