stages:
  - build

build-image:
  stage: build
  image:
    name: moby/buildkit
    entrypoint: [ /bin/sh, -c ]
  tags: [ buildkitd ]
  script:
    - ping -c 1 buildkitd.default.svc.cluster.local
    #- >-
    #  buildctl --addr tcp://127.0.0.1:1234
    #    --tlscacert .certs/client/ca.pem
    #    --tlscert .certs/client/cert.pem
    #    --tlskey .certs/client/key.pem
    #    build --frontend dockerfile.v0 --local context=/path/to/dir --local dockerfile=/path/to/dir
