include:
  - component: '${CI_SERVER_FQDN}/repos/releng/kokkuri/images@2'
  - project: 'repos/releng/docpub'
    file: 'includes/publish.yml'

default:
  tags:
    - kubernetes

stages:
  - test
  - publish
  - build-publish-docs

# Test MRs
.workflow-mr:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# Create a release for each new version tag
.workflow-release:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/
  tags:
    - trusted

# Publish docs when the default branch is updated
.workflow-docs:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

workflow:
  rules:
    - !reference [.workflow-mr, rules]
    - !reference [.workflow-release, rules]
    - !reference [.workflow-docs, rules]

# Build/run tests and build the buildkit gateway and acceptance test runner
# all in one go. Doing this as a single job with bake ensures efficient image
# layer reuse and cache consolidation and cuts down on CI runner utilization.
test:
  stage: test
  extends: [.workflow-mr, .kokkuri:bake, .kokkuri:remote-context]
  variables:
    BUILD_TARGETS: 'test buildkit acceptance'
    TAG: 'job-${CI_JOB_ID}'

# Run acceptance tests
run-acceptance-tests:
  stage: test
  needs: [test]
  extends: [.workflow-mr, .kokkuri:remote-context]
  image: '${TEST_ACCEPTANCE_IMAGE_REF}'
  variables:
    BLUBBER_TEST_IMAGE: '${TEST_BUILDKIT_IMAGE_REF}'
  script:
    - cd /srv/app
    - ./examples.test
  parallel:
    matrix:
      - BLUBBER_ONLY_EXAMPLES: ['@set1', '@set2', '@set3', '@set4']

# Publish a new version of the buildkit frontend each time a tag is pushed or
# an MR is merged to an experimental branch.
build-and-publish-frontend:
  stage: publish
  extends: [.workflow-release, .kokkuri:bake, .kokkuri:remote-context]
  variables:
    BUILD_TARGETS: buildkit
    TAG: '${CI_COMMIT_TAG}'

# Build documentation
build-documentation:
  stage: build-publish-docs
  extends: [.workflow-docs, .kokkuri:bake, .kokkuri:remote-context, .docpub:build-docs]
  variables:
    BUILD_TARGETS: docs
    DOCS_DIR: dist/docs

# Publish documentation to https://doc.wikimedia.org/releng/blubber
publish-documentation:
  stage: build-publish-docs
  needs: [build-documentation]
  extends: [.workflow-docs, .docpub:publish-docs]
